# Generated by Django 3.2.5 on 2021-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='comuna',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='latitud',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitud',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
